// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjURe3rD9w1BTJd8gbbz9KEe9VlKfbU_g',
    appId: '1:392136453535:web:3428b0c23e342daa72a1aa',
    messagingSenderId: '392136453535',
    projectId: 'kinttsugi-app',
    authDomain: 'kinttsugi-app.firebaseapp.com',
    storageBucket: 'kinttsugi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16T9Q1IWrFQIe6myLzbx8Y170HKwWkkE',
    appId: '1:392136453535:android:f8da4de887e05c8e72a1aa',
    messagingSenderId: '392136453535',
    projectId: 'kinttsugi-app',
    storageBucket: 'kinttsugi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxBS88IX2cmMYi0cajWV3jtjvBN-nPTOk',
    appId: '1:392136453535:ios:965a81b3885cdb8c72a1aa',
    messagingSenderId: '392136453535',
    projectId: 'kinttsugi-app',
    storageBucket: 'kinttsugi-app.firebasestorage.app',
    iosBundleId: 'com.kintsugi.kintsugiApp',
  );
}
